version: '3.13.5'
name: stackexchange-agent

services:
  ollama:
    image: ollama/ollama:latest
    container_name: localLLMs
    ports:
      - "11430:11434"
    gpus: all
    pull_policy: missing
    environment:
      - OLLAMA_FLASH_ATTENTION=1
      - OLLAMA_KV_CACHE_TYPE=q4_0
      - OLLAMA_DEBUG=1
      - OLLAMA_MAX_LOADED_MODELS=2
      - OLLAMA_KEEP_ALIVE=-1
      - OLLAMA_NUM_PARALLEL=2
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "ollama", "list" ]
      interval: 10s
      timeout: 5s
      retries: 5

  graphDB:
    container_name: stackexchangeDB
    image: neo4j:5.26
    pull_policy: missing
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_stackexchange_data:/data
      - neo4j_stackexchange_logs:/logs
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*,gds.*
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10

  backend-server:
    build:
      context: .
      dockerfile: backend/Dockerfile
    group_add:
      - "1001" # Your host's docker group GID
    container_name: fastapi-backend
    restart: unless-stopped
    pull_policy: missing
    ports:
      - 8000:8000
    environment:
      - NEO4J_URL=bolt://graphDB:7687
      - NEO4J_USERNAME=${NEO4J_USERNAME}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - OLLAMA_BASE_URL=http://ollama:11434
      - STACKEXCHANGE_API_KEY=${STACKEXCHANGE_API_KEY}
      - HF_HUB_OFFLINE=1
      - HF_HOME=/home/appuser/.cache/huggingface
    volumes:
      - ~/.cache/huggingface:/home/appuser/.cache/huggingface:rw
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        # limits:
        #   # memory: 8G # cap container RAM
        #   cpus: '6' # cap CPU cores
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu, compute, utility ]
    depends_on:
      graphDB:
        condition: service_healthy
      ollama:
        condition: service_healthy

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: streamlit-frontend
    pull_policy: missing
    ports:
      - 8510:8501
    environment:
      - BACKEND_URL=http://backend-server:8000
      - STACKEXCHANGE_API_KEY=${STACKEXCHANGE_API_KEY}
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      backend-server:
        condition: service_started
      ollama:
        condition: service_healthy

networks:
  app-network:
    driver: bridge

volumes:
  neo4j_stackexchange_data:
  neo4j_stackexchange_logs:
  ollama_data:
